# Generated by Django 5.1.7 on 2025-03-24 16:24

import datetime
import django.db.models.deletion
import gallery.models.photo
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_photographer_s3_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_album', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Album UUID')),
                ('name_album', models.CharField(max_length=50, verbose_name='Album name')),
                ('s3_path_album', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Album path S3')),
                ('created_at_album', models.DateTimeField(default=datetime.datetime(2025, 3, 24, 13, 24, 15, 718051), verbose_name='Album creation date')),
                ('updated_at_album', models.DateTimeField(auto_now=True, verbose_name='Album update date')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.photographer', verbose_name='Photographer')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='user.tag', verbose_name='Album tag list')),
            ],
            options={
                'verbose_name': ('Album',),
                'verbose_name_plural': 'Albuns',
                'ordering': ['id', 'name_album'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_photo', models.CharField(max_length=60, verbose_name='Photo name')),
                ('photo', models.FileField(storage=gallery.models.photo.PhotoStorage(), upload_to='')),
                ('s3_path_photo', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Photo path S3')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.album', verbose_name='Photo album')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['id', 'name_photo'],
            },
        ),
    ]
