# Generated by Django 5.1.7 on 2025-03-24 19:03

import gallery.models.photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='uuid_album',
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at_album',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Album creation date'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(max_length=500, storage=gallery.models.photo.PhotoStorage(), upload_to='', verbose_name='Photo file'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='s3_path_photo',
            field=models.CharField(blank=True, editable=False, max_length=500, verbose_name='Photo path S3'),
        ),
    ]
