# Generated by Django 5.1.7 on 2025-03-24 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('name_photographer', models.CharField(max_length=60)),
                ('name_company', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('s3_folder', models.CharField(blank=True, editable=False, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photographer',
                'verbose_name_plural': 'Photographers',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=20, verbose_name='Tag name')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.photographer', verbose_name='Photographer')),
            ],
            options={
                'verbose_name': ('Tag',),
                'verbose_name_plural': 'Tags',
                'ordering': ['id', 'name_tag'],
            },
        ),
    ]
