# Generated by Django 5.1.7 on 2025-03-23 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=20, verbose_name='Tag name')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.photographer', verbose_name='Photographer')),
            ],
            options={
                'verbose_name': ('Tag',),
                'verbose_name_plural': 'Tags',
                'ordering': ['id', 'name_tag'],
            },
        ),
    ]
