# Generated by Django 5.1.7 on 2025-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='s3_folder',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
