# Generated by Django 5.1.7 on 2025-03-23 00:12

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=20, verbose_name='Tag name')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.photographer', verbose_name='Photographer')),
            ],
            options={
                'verbose_name': ('Tag',),
                'verbose_name_plural': 'Tags',
                'ordering': ['id', 'name_tag'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_album', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Album UUID')),
                ('name_album', models.CharField(max_length=50, verbose_name='Album name')),
                ('link_album', models.URLField(verbose_name='Album link')),
                ('created_at_album', models.DateTimeField(default=datetime.datetime(2025, 3, 22, 21, 12, 28, 582881), verbose_name='Album creation date')),
                ('updated_at_album', models.DateTimeField(auto_now=True, verbose_name='Album update date')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.photographer', verbose_name='Photographer')),
                ('tags', models.ManyToManyField(to='album.tag', verbose_name='Album tag list')),
            ],
            options={
                'verbose_name': ('Album',),
                'verbose_name_plural': 'Albuns',
                'ordering': ['id', 'name_album'],
            },
        ),
    ]
