# Generated by Django 5.1.7 on 2025-03-23 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('user', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at_album',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 23, 16, 47, 53, 116743), verbose_name='Album creation date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(to='user.tag', verbose_name='Album tag list'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
